// Excursiones
export const EXCURSIONES_LOADING = 'EXCURSIONES_LOADING';
export const ADD_EXCURSIONES = 'ADD_EXCURSIONES';
export const EXCURSIONES_FAILED = 'EXCURSIONES_FAILED';

// Comentarios
export const ADD_COMENTARIOS = 'ADD_COMENTARIOS';
export const COMENTARIOS_FAILED = 'COMENTARIO_FAILED';
export const POST_COMENTARIO = 'POST_COMENTARIO';
export const ADD_COMENTARIO = 'ADD_COMENTARIO';

// Cabecera
export const CABECERAS_LOADING = 'CABECERA_LOADING';
export const ADD_CABECERAS = 'ADD_CABECERA';
export const CABECERAS_FAILED = 'CABECERA_FAILED';

// Actividades
export const ACTIVIDADES_LOADING = 'ACTIVIDADES_LOADING';
export const ADD_ACTIVIDADES = 'ADD_ACTIVIDADES';
export const ACTIVIDADES_FAILED = 'ACTIVIDADES_FAILED';

// Usuario
export const CARGAR_USUARIO = 'CARGAR_USUARIO';
export const ACTUALIZAR_USUARIO = 'ACTUALIZAR_USUARIO';
export const ACTUALIZAR_FAVORITOS = 'ACTUALIZAR_FAVORITOS';
export const BORRAR_FAVORITOS = 'BORRAR_FAVORITOS';